config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tops#index"
  #top
  get 'tops', to: 'tops#index'
  get 'tops/lists', to: 'tops#lists'
  post 'tops/lists', to: 'tops#lists'

  #reviews
  get 'reviews', to: 'reviews#index'
  post 'reviews', to: 'reviews#index'
  get 'reviews/add_review', to: 'reviews#add_review'
  post 'reviews/create', to: 'reviews#create'
  get 'reviews/detail', to: 'reviews#detail'
  post 'reviews/detail', to: 'reviews#detail'
  #empathies
  post 'empathies/create', to: 'empathies#create'
  delete 'empathies/delete', to: 'empathies#delete'
  #Performance_search
  post 'performance_search/search', to: 'performance_search#search'

  #login
  get 'login', to: 'login#index'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'

  #add_user
  get 'add_users', to: 'add_users#index'
  post 'add_users/confirm', to: 'add_users#confirm'  
  post 'add_users/create', to: 'add_users#create'
  
  #profile
  get 'profiles', to: 'profiles#index'
  get 'profiles/edit_profile', to: 'profiles#edit_profile'
  patch 'profiles/update', to: 'profiles#update'
  get 'profiles/pass', to: 'profiles#pass'
  put 'profiles/pass_update', to: 'profiles#pass_update'
  get 'profiles/display_profile', to: 'profiles#display_profile'
  #delere_reviews
  put 'delete_reviews/update', to: 'delete_reviews#update'

  #other_add
  get 'other_add', to: 'other_add#index'
  post 'other_add/create', to: 'other_add#create'
  get 'other_add/edit', to: 'other_add#edit'
  patch 'other_add/update', to: 'other_add#update'
  get 'other_add/test', tp: 'other_add#test'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def index
        @reviews =  Review.joins("INNER JOIN gadgets ON gadgets.id = reviews.gadget_id").select("gadgets.gadget_name ,reviews.*").where(reviews: {user_id: current_user.id}).order(id: "DESC")    
        @good_sum = Review.joins("INNER JOIN empathies ON empathies.review_id = reviews.id").joins("INNER JOIN users ON users.id = reviews.user_id").select("users.user_name, count(empathies.review_id) num_emp").group("users.user_name").order("num_emp desc").where(reviews: {user_id: current_user.id})
    end

    def edit_profile
        @user = User.find(current_user.id)
    end

    def update
        User.find(current_user.id).update(profile_update_params)
        redirect_to profiles_path 
    end

    def pass
        @user = User.new
    end

    def pass_update
        User.find(current_user.id).update(pass_update_params)
        redirect_to profiles_path 
    end

    def display_profile
        key = params[:id]
        @user = User.find(key)
        @reviews =  Review.joins("INNER JOIN gadgets ON gadgets.id = reviews.gadget_id").select("gadgets.gadget_name ,reviews.*").where(reviews: {user_id: key}).order(id: "DESC")    
        @good_sum = Review.joins("INNER JOIN empathies ON empathies.review_id = reviews.id").joins("INNER JOIN users ON users.id = reviews.user_id").select("users.user_name, count(empathies.review_id) num_emp").group("users.user_name").order("num_emp desc").where(reviews: {user_id: key})
    end   

    private
    def profile_update_params
        params.require(:user).permit(:user_name, :birthday, :gender, :mail, :mail_sub, :user_image)
    end

    def pass_update_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/display_profile.html.erb
<div class="container-fluid">
    <div class="row bg-light"><br><br></div>
    <div class="row bg-light">
        <div class="col-1"></div>
        <div class="col-4">
            <div class="bg-white p-3">
                <h5 class="">ユーザー名：<span class="ml-2"><%= @user.user_name %></span></h5>
                <h5>貰った役に立った数:
                    <% @good_sum.each do |disp|%>
                        <%= disp.num_emp %>
                    <% end %>
                </h5>
                <div class="bg-light mt-3 mb-4">
                <% if @user.user_image.blank? %>
                    <img src="guest.png" class="img-responsive mx-auto d-block img-thumbnail">
                <% else %>
                    <img src="<%= @user.user_image %>" class="img-responsive mx-auto d-block img-thumbnail">
                <% end %>
                </div>
            </div>
        </div>
        <div class="col-6 bg-white">
            <h5 class="text-center mt-3"><%= @user.user_name %>さんの投稿履歴</h5>
            <% @reviews.each do |disp| #ユーザーが過去に投稿したレビューを表示する。 %>
                <% if disp.delete_flag == 0  #delete_falgが0のレビューだけを表示する。 %>
                    <div class="card border-0 bg-white">
                        <div class="card-body">
                            <div class="text-center">
                            <span>投稿したガジェット：</span><span class="ml-2"><%= link_to disp.gadget_name, reviews_path(id: disp.gadget_id)  %></span>
                            </div>
                            <div class="card-header bg-white mb-1 border-0">
                                <div class="row">
                                    <div class="col-8"><img src="<%= @user.user_image %>" class="" width="30" height="auto"></img>
                                    <span class="ml-3"><%= @user.user_name %></span></div>     
                                    <div class="col-4 text-right "><%= disp.updated_at.strftime("%Y/%m/%d/%H:%M") %></div>
                                </div>    
                            </div><!--card-header-->
                            <ul class="nav nav-tabs">
                                <li class="nav-item">
                                    <a href="#good_point<%= disp.id %>" class="nav-link active" data-toggle="tab">良かった点</a>
                                </li> 
                                <li class="nav-item">
                                    <a href="#bad_point<%= disp.id %>" class="nav-link text-danger" data-toggle="tab">悪かった点</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#image<%= disp.id %>" class="nav-link text-muted" data-toggle="tab">画像</a>
                                </li>
                            </ul><!--nav-tabs-->
                            <div class="tab-content border-bottom border-left border-right rounded-bottom">
                                <div id="good_point<%= disp.id %>" class="tab-pane active">
                                    <div class="mb-1"> 
                                        <div class="card-body">
                                            <p class="card-text mt-3">
                                            <%= disp.good_review %>
                                            </p>
                                        </div>
                                    </div>
                                </div><!--good_point-->
                                <div id="bad_point<%= disp.id %>" class="tab-pane">
                                    <div class="mb-1">
                                        <div class="card-body">
                                            <p class="card-text mt-3">
                                                <%= disp.bad_review %>
                                            </p>
                                        </div>
                                    </div>
                                </div><!--bad_point-->
                                <div id="image<%= disp.id %>" class="tab-pane">
                                    <div class="mb-1">
                                        <div class="card-body">
                                        <img src="<%= disp.image %>" class="img-responsive mx-auto d-block img-thumbnail">
                                    </div>
                                </div><!--image-->
                            </div><!--tab-content-->
                        </div><!--card-body-->      
                        <div class="text-right mt-3">
                            <span class="mr-3"><label>役に立った数：<%= disp.empathies.length %></span></label>      
                        </div>
                    </div><!--card--> 
                    <hr>  
                <% end %>          
            <% end %>
        </div>
        <div class="col-1"></div>
    </div>
</div>

app/views/profiles/edit_profile.html.erb
<div class="container-fluid">
<div class="row bg-light"><br><br></div>
<%= form_for @user, url: profiles_update_path do |f| %>
<div class="row bg-light">
    <div class="col-1"></div>
    <div class="col-4">
        <div class="bg-white p-3">
            <h5 class=""><%= current_user.user_name %></h5>
            <div class="bg-light mt-3 mb-4">
            <% if current_user.user_image.blank? %>
                初期設定です。
            <% else %>
                <img src="<%= current_user.user_image %>" class="img-responsive mx-auto d-block img-thumbnail">
            <% end %>
            </div>
            <%= f.file_field :user_image %>
        </div>
    </div>
    <div class="col-6 bg-white p-5">
                <table class="ml-auto mr-auto">
                    <tr>                       
                        <th style="width:25%">ユーザー名</th>
                        <td style="width:75%" colspan="2">
                        <%= f.text_field :user_name, class: "form-control col-8 ml-2", style: "",placeholder: "ユーザー名",id: "user_name_add" %>
                        </td>                                   
                    </tr>
                    <tr><td><br></td></tr>
                    <tr>                        
                        <th style="width:25%">性別</th>
                        <td style="width:75%" class="pl-2" colspan="2">
                            <%= f.radio_button :gender, "男性",checked: true %>
                            <%= f.label :gender_man, "男性" %>
                            <%= f.radio_button :gender, "女性" %>
                            <%= f.label :gender_women, "女性" %>
                            <%= f.radio_button :gender, "その他" %>
                            <%= f.label :gender_others, "その他" %>
                        </td>                                       
                    </tr>
                    <tr><td><br></td></tr>
                    <tr>                        
                        <th style="width:25%">生年月日</th>
                        <td style="width:75%" colspan="2">
                            <%= f.text_field :birthday, class: "form-control col-8 ml-2", placeholder: "1990年1月05日→19900105",id: "birthday_add" %>
                        </td>                                     
                    </tr>
                    <tr><td></td><td colspan="2"><div id="miss_birthday" class="m-1 alert" ></div></td></tr>      
                    <tr>                       
                        <th style="width:25%">メールアドレス</th>
                        <td style="width:75%" colspan="2">
                        <%= f.text_field :mail, class: "form-control col-8 ml-2",placeholder: "メールアドレス", onBlur: "seikicheck();",id: "mail_add1" %>
                        </td>                         
                    </tr>
                    <tr><td></td><td colspan="2"><div id="miss_mail1" class="m-1 alert" ></div></td></tr>
                    <tr>                       
                        <th style="width:25%">メールアドレス確認</th>
                        <td style="width:75%" colspan="2">
                        <%= f.text_field :mail_sub, class: "form-control col-8 ml-2", placeholder: "メールアドレス確認", onBlur: "mailcheck();",id: "mail_add2" %>
                        </td>                             
                    </tr>
                </table>
                <%= submit_tag("アカウント情報変更", class: "btn btn-danger mx-auto d-block w-50 mt-5", onClick: "return check();") %>         
         <% end %>
    </div>
    <div class="col-1"></div>
</div>
</div>

app/views/profiles/index.html.erb
<div class="container-fluid">
    <div class="row bg-light"><br><br></div>
    <div class="row bg-light">
        <div class="col-1"></div>
        <div class="col-4">
            <div class="bg-white p-3">
                <h5 class="">ユーザー名：<span class="ml-2"><%= current_user.user_name %></span></h5>
                <h5>貰った役に立った数:
                    <% @good_sum.each do |disp|%>
                        <%= disp.num_emp %>
                    <% end %>
                </h5>
                <div class="bg-light mt-3 mb-4">
                <% if current_user.user_image.blank? %>
                    <img src="guest.png" class="img-responsive mx-auto d-block img-thumbnail">
                <% else %>
                    <img src="<%= current_user.user_image %>" class="img-responsive mx-auto d-block img-thumbnail">
                <% end %>
                </div>
                <%= link_to "登録情報変更", profiles_edit_profile_path ,class: "btn btn-primary form-control"%>
                <%= link_to "パスワード変更", profiles_pass_path ,class: "btn btn-success form-control mt-3 mb-3"%>
            </div>
        </div>
        <div class="col-6 bg-white">
            <h5 class="text-center mt-3"><%= current_user.user_name %>さんの投稿履歴</h5>
            <% @reviews.each do |disp| #ユーザーが過去に投稿したレビューを表示する。 %>
                <%= render :partial => "delete_reviews/delete_review", :locals => { disp: disp } %>           
            <% end %>
        </div>
        <div class="col-1"></div>
    </div>
</div>

app/views/profiles/pass.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-2"></div>
            <div class="col-8 bg-white p-5">
                <%= form_for @user, url: profiles_pass_update_path,method: :put do |f| %>
                    <h5 class="text-center mb-5">パスワードを変更する。</h5>
                    <div class="form-group">
                    <%= f.password_field :password, class: "form-control mx-auto d-block mt-1", style: "width:30rem;",placeholder: "パスワード" %>
                    <%= f.password_field :password_confirmation, class: "form-control mx-auto d-block mt-1", style: "width:30rem;",placeholder: "パスワード確認" %>
                    <button type="button" class="btn btn-danger mx-auto d-block w-50 mt-5" data-toggle="modal" data-target="#PassAlertModal">パスワードを変更する</button>                             
                    <!--モーダル-->
                    <div class="modal" id="PassAlertModal" tabindex="-1" role="dialog" aria-labelledby="PassAlertModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5>パスワードを変更しますか？</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times</span>
                                </button>
                                </div><!--モーダルヘッダー-->
                                <div class="modal-footer">
                                    <%= submit_tag("変更する", class: "btn btn-danger ml-auto-5")%>  
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>
                                </div>
                            </div><!--モーダルコンテンツ-->
                        </div><!--モーダルダイアログ本体-->
                    </div><!--モーダル外枠-->
                    <!--モーダル-->
                <% end %>  
                <hr>    
                <%= link_to "プロフィールへ戻る", profiles_path(id: current_user.id) ,class: "btn btn-primary mx-auto d-block w-50 m-3"%>
            </div>
        <div class="col-2"></div>    
    </div>
    <div class="row">
    <br><br><br><br><br><br><br><br><br>
    </div>
</div>