config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tops#index"
  #top
  get 'tops', to: 'tops#index'
  get 'tops/lists', to: 'tops#lists'
  post 'tops/lists', to: 'tops#lists'

  #reviews
  get 'reviews', to: 'reviews#index'
  post 'reviews', to: 'reviews#index'
  get 'reviews/add_review', to: 'reviews#add_review'
  post 'reviews/create', to: 'reviews#create'
  get 'reviews/detail', to: 'reviews#detail'
  post 'reviews/detail', to: 'reviews#detail'
  #empathies
  post 'empathies/create', to: 'empathies#create'
  delete 'empathies/delete', to: 'empathies#delete'
  #Performance_search
  post 'performance_search/search', to: 'performance_search#search'

  #login
  get 'login', to: 'login#index'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'

  #add_user
  get 'add_users', to: 'add_users#index'
  post 'add_users/confirm', to: 'add_users#confirm'  
  post 'add_users/create', to: 'add_users#create'
  
  #profile
  get 'profiles', to: 'profiles#index'
  get 'profiles/edit_profile', to: 'profiles#edit_profile'
  patch 'profiles/update', to: 'profiles#update'
  get 'profiles/pass', to: 'profiles#pass'
  put 'profiles/pass_update', to: 'profiles#pass_update'
  get 'profiles/display_profile', to: 'profiles#display_profile'
  #delere_reviews
  put 'delete_reviews/update', to: 'delete_reviews#update'

  #other_add
  get 'other_add', to: 'other_add#index'
  post 'other_add/create', to: 'other_add#create'
  get 'other_add/edit', to: 'other_add#edit'
  patch 'other_add/update', to: 'other_add#update'
  get 'other_add/test', tp: 'other_add#test'
end

app/controllers/other_add_controller.rb
class OtherAddController < ApplicationController
    def index
        @gadget = Gadget.new
        @gadget_view = Gadget.all
    end

    def create
        @g = gadget_params
        Gadget.create(gadget_params)
        gad = Gadget.order(created_at: :desc).limit(1)
        gad.update(review_point: 0, performance_point: 0, design_point: 0, costperformance_point: 0, feel_point: 0)
        #redirect_to '/other_add' 
    end

    def edit
        @id = params[:id]
        @gadget = Gadget.find(@id)
    end

    def update    
        Gadget.find(params[:id]).update(gadget_update_params)
        redirect_to '/other_add' 
    end
    #デモンストレーション用のコード
    def test
        @review_del = Review.maximum(:id)
        Review.find(@review_del).destroy
        redirect_to '/other_add'
    end

    private
    def gadget_params
        params.require(:gadget).permit(:gadget_name, :gadget_info, :gadget_url, :category_id, :image, :release_date)
    end

    def gadget_update_params
        params.require(:gadget).permit(:gadget_name, :gadget_info, :gadget_url, :category_id, :release_date)
    end

end

app/helpers/other_add_helper.rb
module OtherAddHelper
end

app/views/other_add/create.html.erb
<%= @g %>

app/views/other_add/edit.html.erb
<h2><%= @id %></h2>
<%= form_for @gadget, url: other_add_update_path(id: @gadget.id) do |f| %>
  ガジェット名：<br>
  <%= f.text_field :gadget_name %><br>
  ガジェット情報：<br>
  <%= f.text_area :gadget_info , size: "100x15"%><br>
  ガジェットカテゴリー：<br>
  <%= f.text_field :category_id %><br>
  ガジェットURL：<br>
  <%= f.text_field :gadget_url ,style: "width:50rem"%><br>
  ガジェット画像<br>
  <%= f.text_field :image ,style: "width:50rem" %><br>
  発売日<br>
  <%= f.text_field :release_date %><br>
  <%= f.submit '完了' %>
<% end %>

app/views/other_add/index.html.erb
<%= link_to "削除", other_add_test_path, class: "btn btn-danger m-3" %>
<div>
<%= form_for @gadget, url: other_add_create_path do |f| %>
  ガジェット名：<br>
  <%= f.text_field :gadget_name %><br>
  ガジェット情報：<br>
  <%= f.text_area :gadget_info , size: "100x15"%><br>
  ガジェットカテゴリー：<br>
  <%= f.text_field :category_id %><br>
  ガジェットURL：<br>
  <%= f.text_field :gadget_url %><br>
  ガジェット画像<br>
  <%= f.file_field :image %><br>
  発売日<br>
  <%= f.text_field :release_date %><br>
  <%= f.submit '完了' %>
<% end %>

<table>
<tr>
<th>id</th>
<th>gadget_name</th>
<th>update</th>
</tr>
<% @gadget_view.each do |show| %>
  <tr>
  <td><%= show.id %></td>
  <td><%= show.gadget_name %></td>
  <td><%= link_to "update",  other_add_edit_path(id: show.id)%></td>
  <tr>
<% end %>
</table>
</div>

app/views/other_add/test.html.erb
<%= @review_del %>