config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tops#index"
  #top
  get 'tops', to: 'tops#index'
  get 'tops/lists', to: 'tops#lists'
  post 'tops/lists', to: 'tops#lists'

  #reviews
  get 'reviews', to: 'reviews#index'
  post 'reviews', to: 'reviews#index'
  get 'reviews/add_review', to: 'reviews#add_review'
  post 'reviews/create', to: 'reviews#create'
  get 'reviews/detail', to: 'reviews#detail'
  post 'reviews/detail', to: 'reviews#detail'
  #empathies
  post 'empathies/create', to: 'empathies#create'
  delete 'empathies/delete', to: 'empathies#delete'
  #Performance_search
  post 'performance_search/search', to: 'performance_search#search'

  #login
  get 'login', to: 'login#index'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'

  #add_user
  get 'add_users', to: 'add_users#index'
  post 'add_users/confirm', to: 'add_users#confirm'  
  post 'add_users/create', to: 'add_users#create'
  
  #profile
  get 'profiles', to: 'profiles#index'
  get 'profiles/edit_profile', to: 'profiles#edit_profile'
  patch 'profiles/update', to: 'profiles#update'
  get 'profiles/pass', to: 'profiles#pass'
  put 'profiles/pass_update', to: 'profiles#pass_update'
  get 'profiles/display_profile', to: 'profiles#display_profile'
  #delere_reviews
  put 'delete_reviews/update', to: 'delete_reviews#update'

  #other_add
  get 'other_add', to: 'other_add#index'
  post 'other_add/create', to: 'other_add#create'
  get 'other_add/edit', to: 'other_add#edit'
  patch 'other_add/update', to: 'other_add#update'
  get 'other_add/test', tp: 'other_add#test'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
require 'bigdecimal'
    def index
        key = params[:id]
        @gadget = Gadget.find(key)
        @reviews = Review.joins("INNER JOIN users ON users.id = reviews.user_id").select("users.user_name ,users.user_image, users.id AS ID, reviews.*").where(reviews: { gadget_id: key})
        @test = @reviews.empty?    
    end

    def add_review
        @review = Review.new
        @gadget_id = params[:id]
    end

    def create
        if request.post? then
            gadget_id = params[:id]
            Review.create(review_add_params)
            review_point = Review.order(created_at: :desc).limit(1)
            #pythonスクリプトreview_pointを動かしてレビューの得点を出す
            p_point = `python lib/assets/python/review_point.py`
            review_point.update(review_point: p_point)

            avg = Review.where(gadget_id: gadget_id).where(delete_flag: 0).where.not(review_point: 0).average(:review_point)
            #pythonスクリプトbayes_readを動かしてそれぞれの項目の得点を出す。
            data = `python lib/assets/python/bayes_read.py "#{gadget_id}"`
            #それぞれの項目数値を配列に分ける。
            data = data.split(" ")
            rev_avg = (BigDecimal(avg) + BigDecimal(data[0]) + BigDecimal(data[1]) + BigDecimal(data[2]) + BigDecimal(data[3]))/5
            Gadget.where(id: gadget_id).update(review_point: rev_avg, performance_point: data[0], design_point: data[1], costperformance_point: data[2], feel_point: data[3])
        end
        redirect_to reviews_path(id: gadget_id)
    end

    private
    def review_add_params
        params.require(:review).permit(:good_review, :bad_review, :user_id, :gadget_id, :image, :delete_flag)
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/add_review.html.erb
<%= javascript_pack_tag 'review_check'%>
<div class="container-fluid">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <br><br><br><br>
            <h5 class="text-center font-weight-bolder">レビュー内容をお書きください。</h5>
            <br><br><br><br>
        </div> 
        <div class="col-1"></div>   
    </div>
    <br>
    <div class="row">    
        <div class="col-2"></div>
        <div class="col-8">
            <%= form_for @review, url: reviews_create_path(id: @gadget_id) do |f| %>
                <div class="row">
                    <label class="text-danger font-weight-bolder col-6">良かった点</label>
                    <label class="text-primary font-weight-bolder col-6">悪かった点</label>
                </div>
                <div class="row">
                    <div class="form-group col-6"><%= f.text_area :good_review, size: "1000x20",class: "form-control",id: "good_review" %></div> 
                    <div class="form-group col-6"><%= f.text_area :bad_review, size: "1000x20",class: "form-control", id: "bad_review" %></div>                
                </div>      
                <div class="form-group row">              
                    <%= f.file_field :image, style: "", class: "form-control-file ml-3" %>
                </div>   
                <%= f.hidden_field :gadget_id, :value => @gadget_id %>
                <%= f.hidden_field :user_id, :value => current_user.id %> 
                <%= f.hidden_field :delete_flag, :value => 0 %>          
                <%= submit_tag("送信", class: "btn btn-primary float-right mr-2",id: "start2",onClick: "return rev_check();")%>   
                <input type="reset" value="リセット" class="btn btn-primary float-right mr-2"> 
            <% end %>             
        </div>
        <div class="col-2"></div>
    </div>   
</div>

app/views/reviews/detail.html.erb
<div class="container-fluid bg-light">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-10">
        </div>
        <br><br>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-4">
        <div class=" pt-3 bg-white">
        <h4 class="text-center"><%= @gadget.gadget_name %></h4>
            <div class="mb-5">
                <img border="1" src="<%= @gadget.image %>" height="250rem" alt="ガジェット画像" class= "d-block ml-auto mr-auto">
                <% if @gadget.review_point != nil %>
                <div class="text-center h5 mt-3">
                    総合評価点：<%= @gadget.review_point.round(2) %>/5.00<br>
                    <span class="rate rate<%= (@gadget.review_point.round(1) * 10).floor %>"></span>  
                </div>   
                <% end %>               
                <p class="pt-4 pr-4 pl-4 card-text">製品情報:<br><%= @gadget.gadget_info %></p>
                <% if @gadget.gadget_url.empty? %>
                    <p class="pr-4 pl-4 card-text text-center">製品ページがありません。</p>
                <% else %>
                    <p class="pr-4 pl-4 card-text text-center"><%= link_to '製品ページへ行く', @gadget.gadget_url %></p>
                <% end %>
                <% if logged_in? %>
                    <%= link_to "レビューする", reviews_add_review_path(id: @gadget.id) ,class: "btn btn-primary d-block mx-auto"%>
                <% else %>
                    <%= link_to "レビューする", login_path ,class: "btn btn-primary d-block mx-auto"%>
                <% end %>
                <br>
                    <%= link_to "レビューを見る", reviews_path(id: @gadget.id) ,class: "btn btn-danger d-block mx-auto"%>
                <br>                
            </div>    
        </div>    
        </div>
        
        <div class="col-6 pr-0 bg-white">
        <%= @data %>
        </div>
        <div class="col-1"></div>
    </div>
    <div class="row">
    
    </div>
</div>

app/views/reviews/index.html.erb
<div class="container-fluid bg-light">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-10">
        </div>
        <br><br>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-4">
        <div class=" pt-3 bg-white">
        <h4 class="text-center"><%= @gadget.gadget_name %></h4>
            <div class="mb-5">
                <img border="1" src="<%= @gadget.image %>" height="250rem" alt="ガジェット画像" class= "d-block ml-auto mr-auto">
                <br>
                <table border="0" class = "ml-auto mr-auto">
                    <tr>
                    <td class="text-right">総合点：</td>
                    <td><span class="rate rate<%= (@gadget.review_point.round(1) * 10).floor %>"></span></td>
                    <td class="text-right"><%= @gadget.review_point.round(2) %>/5.00</td>
                    </tr>
                    <tr>
                    <td class="text-right">性能：</td>
                    <td><span class="rate rate<%= (@gadget.performance_point.round(1) * 10).floor %>"></span></td>
                    <td class="text-right"><%= @gadget.performance_point.round(2) %>/5.00</td>
                    </tr>
                    <tr>
                    <td class="text-right">デザイン：</td>
                    <td><span class="rate rate<%= (@gadget.design_point.round(1) * 10).floor %>"></span></td> 
                    <td class="text-right"><%= @gadget.design_point.round(2) %>/5.00</td>
                    </tr>
                    <tr>
                    <td class="text-right">コスパ：</td>
                    <td><span class="rate rate<%= (@gadget.costperformance_point.round(1) * 10).floor %>"></span></td>
                    <td class="text-right"><%= @gadget.costperformance_point.round(2) %>/5.00</td>
                    </tr>
                    <tr>
                    <td class="text-right">使用感：</td>
                    <td><span class="rate rate<%= (@gadget.feel_point.round(1) * 10).floor %>"></span></td>
                    <td class="text-right"><%= @gadget.feel_point.round(2) %>/5.00</td>
                    </tr> 
                </table> 
                <p class="pt-4 pr-4 pl-4 card-text">製品情報:<br><%= @gadget.gadget_info %></p>
                <% if @gadget.gadget_url.empty? %>
                    <p class="pr-4 pl-4 card-text text-center">製品ページがありません。</p>
                <% else %>
                    <p class="pr-4 pl-4 card-text text-center"><%= link_to '製品ページへ行く', @gadget.gadget_url %></p>
                <% end %>
                <% if logged_in? %>
                    <%= link_to "レビューする", reviews_add_review_path(id: @gadget.id) ,class: "btn btn-primary d-block mx-auto"%>
                <% else %>
                    <%= link_to "レビューする", login_path ,class: "btn btn-primary d-block mx-auto"%>
                <% end %>
                <br>           
            </div>    
        </div>    
        </div>
        
        <div class="col-6 pr-0">
        <%= @reviews_test %>
            <% if @test == true %>
            <div class="card border-0 bg-white">
                <div class="card-body">
                    現在投稿はありません。
                </div>
            </div>    
            <% end %>
            <% @reviews.reverse_each do |disp| #レビューを表示する %>
                <% if disp.delete_flag == 0  #delete_falgが0のレビューだけを表示する。 %>
                    <div class="card border-0 bg-white">
                        <div class="card-body">
                            <div class="card-header bg-white mb-1 border-0">
                                <div class="row">
                                    <div class="col-6">
                                    <% if disp.user_image.blank? %>
                                        <img src="guest.png" class="" width="30" height="auto">
                                    <% else %>    
                                        <img src="uploads/user/user_image/<%= disp.ID %>/<%= disp.user_image %>" class="" width="30" height="auto">
                                    <% end %>
                                    <span class="ml-3"><%= disp.user_name %></span></div>
                                    <div class="col-6 text-right">
                                    投稿日時：<%= disp.updated_at.strftime("%Y/%m/%d/%H:%M") %>
                                    </div>
                                </div>    
                                <div class="row">
                                    <% if disp.review_point != nil && disp.review_point != 0 %>
                                        <div class="col text-right">
                                        評価点：<%= disp.review_point.round(2) %>/5.00<br>
                                        <span class="rate rate<%= (disp.review_point.round(1) * 10).floor %>"></span>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="nav-item">
                                    <a href="#good_point<%= disp.id %>" class="nav-link active" data-toggle="tab">良かった点</a>
                                </li> 
                                <li class="nav-item">
                                    <a href="#bad_point<%= disp.id %>" class="nav-link text-danger" data-toggle="tab">悪かった点</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#image<%= disp.id %>" class="nav-link text-muted" data-toggle="tab">画像</a>
                                </li>
                            </ul>
                            <div class="tab-content border-bottom border-left border-right rounded-bottom">
                                <div id="good_point<%= disp.id %>" class="tab-pane active">
                                    <div class="mb-1"> 
                                        <div class="card-body">
                                            <p class="card-text mt-3">
                                            <%= disp.good_review %>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div id="bad_point<%= disp.id %>" class="tab-pane">
                                    <div class="mb-1">
                                        <div class="card-body">
                                            <p class="card-text mt-3">
                                            <%= disp.bad_review %>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div id="image<%= disp.id %>" class="tab-pane">
                                    <div class="mb-1">
                                        <div class="card-body">
                                        <img src="<%= disp.image %>" class="img-responsive mx-auto d-block img-thumbnail">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <div class="btn-toolbar" id="foot-<%= disp.id %>">
                            <%= render :partial => "empathies/empathy", :locals => { disp: disp } %> 
                        </div><!--btn-toolbar-->    
                        </div>
                    </div> 
                    <hr>
                <% end #delete_falgが0のレビューだけを表示する %>    
            <% end #レビューを表示する %>  
        </div>
        <div class="col-1"></div>
    </div>
    <div class="row">
    
    </div>
</div>