config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tops#index"
  #top
  get 'tops', to: 'tops#index'
  get 'tops/lists', to: 'tops#lists'
  post 'tops/lists', to: 'tops#lists'

  #reviews
  get 'reviews', to: 'reviews#index'
  post 'reviews', to: 'reviews#index'
  get 'reviews/add_review', to: 'reviews#add_review'
  post 'reviews/create', to: 'reviews#create'
  get 'reviews/detail', to: 'reviews#detail'
  post 'reviews/detail', to: 'reviews#detail'
  #empathies
  post 'empathies/create', to: 'empathies#create'
  delete 'empathies/delete', to: 'empathies#delete'
  #Performance_search
  post 'performance_search/search', to: 'performance_search#search'

  #login
  get 'login', to: 'login#index'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'

  #add_user
  get 'add_users', to: 'add_users#index'
  post 'add_users/confirm', to: 'add_users#confirm'  
  post 'add_users/create', to: 'add_users#create'
  
  #profile
  get 'profiles', to: 'profiles#index'
  get 'profiles/edit_profile', to: 'profiles#edit_profile'
  patch 'profiles/update', to: 'profiles#update'
  get 'profiles/pass', to: 'profiles#pass'
  put 'profiles/pass_update', to: 'profiles#pass_update'
  get 'profiles/display_profile', to: 'profiles#display_profile'
  #delere_reviews
  put 'delete_reviews/update', to: 'delete_reviews#update'

  #other_add
  get 'other_add', to: 'other_add#index'
  post 'other_add/create', to: 'other_add#create'
  get 'other_add/edit', to: 'other_add#edit'
  patch 'other_add/update', to: 'other_add#update'
  get 'other_add/test', tp: 'other_add#test'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>裏表ガジェットレビュー</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <header class="sticky-top shadow-sm">
      <div class="row bar_color">
        <div class="col-1">
        <!--余白-->
        </div>
        <div class="navbar navbar-expand-lg col-5 align-self-center" role="navigation">
          <a class="text-white font-weight-bolder h3" href="/tops">
          裏表ガジェットレビュー
          </a>
        </div>
        <div class="navbar navbar-expand-lg col-5 align-self-center">   
          <div class="ml-auto">                           
            <%= form_tag(tops_lists_path, method: :post) do %> 
            <div class="form-row">  
              <div class="col-auto">                  
              <%= text_field_tag :search_gadgets,"" , placeholder: "ガジェット検索" , class: "form-control-sm" %>            
              </div>
              <div class="col-auto">
              <%= submit_tag "Search", class: "btn btn-success btn-sm mr-2"%>
              </div>      
            <% end %>
              <% if logged_in? %>           
                <button type="button" class="btn btn-sm text-white" data-toggle="modal" data-target="#LogoutAlertModal">ログアウト</button>  
                <%= link_to current_user.user_name, profiles_path, class: "btn btn-sm text-white" %>
              <% else %>
                <%= link_to "ログイン", login_path, class: "btn btn-sm text-white mr-2" %>   
                <%= link_to "新規登録", add_users_path, class: "btn btn-sm text-white" %>   
              <% end %><!--logged_in?--> 
            </div><!--form-row-->        
          </div><!--ml-auto-->   
        </div><!--navbar-->
        <div class="col-1">
        <!--余白-->
        </div>
      </div>
    </header>

      <!--モーダル-->
        <div class="modal" id="LogoutAlertModal" tabindex="-1" role="dialog" aria-labelledby="LogoutAlertModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
              <h5>ログアウトしますか？</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times</span>
                </button>
              </div><!--モーダルヘッダー-->
              <div class="modal-footer">
                <%= link_to "ログアウト", logout_path, method: :delete, class: "btn btn-danger ml-auto" %>
                <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>
              </div>
            </div><!--モーダルコンテンツ-->
          </div><!--モーダルダイアログ本体-->
        </div><!--モーダル外枠-->
      <!--モーダル-->

    <%= yield %>
    
  </body>
</html>